// Rewrites incoming viewer requests so that CloudFront resolves the correct
// S3 object for directory-style URLs generated by static site frameworks
// (Gatsby, Next.js, etc.).
//
// Examples:
//   /          -> /index.html   (root already handled by default_root_object,
//                                 but included here for safety)
//   /about/    -> /about/index.html
//   /blog/     -> /blog/index.html
//   /blog/my-post/ -> /blog/my-post/index.html
//
// Requests that already include a file extension are passed through unchanged.
function handler(event) {
    var request = event.request;
    var uri = request.uri;

    if (uri.endsWith('/')) {
        request.uri += 'index.html';
    } else if (!uri.split('/').pop().includes('.')) {
        request.uri += '/index.html';
    }

    return request;
}
