output "cdn_domain" {
  description = "The CloudFront domain autogenerated by AWS."
  value       = aws_cloudfront_distribution.cloudfront.domain_name
}

output "cdn_id" {
  description = "The CloudFront distribution ID."
  value       = aws_cloudfront_distribution.cloudfront.id
}

output "s3_origin_bucket" {
  description = "The origin bucket Cloudfront will use to get the content."
  value       = aws_s3_bucket.cloudfront.id
}

output "external_id" {
  description = <<DESC
The external ID to be passed using the `--external-id` flag of the
`aws sts assume-role` command.
DESC
  value       = random_string.external_id.result
}

output "cicd_role_arn" {
  description = "The ARN of the generated role."
  value       = aws_iam_role.cloudfront.arn
}